from typing import Protocol


class TacosDatabaseProtocol(Protocol):
    def get_tacos_count(self, guild_id: int, user_id: int) -> int: ...
    def remove_all_tacos(self, guild_id: int, user_id: int) -> None: ...
    def add_taco_gift(self, guild_id: int, user_id: int, amount: int) -> None: ...
    def get_total_gifted_tacos(self, guild_id: int, user_id: int, timespan: int) -> int: ...
    def get_taco_reaction(self, guild_id: int, user_id: int, channel_id: int, message_id: int) -> bool: ...
    def add_taco_reaction(self, guild_id: int, user_id: int, channel_id: int, message_id: int) -> None: ...
