{
 "title": "Tacobot",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "guild_id", "label": "Guild", "query": { "query": "tacobot_guilds" } }
  ]
 },
 "panels": [
  { "title": "BIRD'S EYE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TACOBOT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B + $C", "type": "math" }
   ]
  },
  {
   "title": "SHORTNR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"shortnr\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "MONGODB BACKUP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mgob\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "SHORTNR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"shortnr\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "TOKENS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(nus_tokens or vector(0))", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "SHORTENS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(nus_shorten or vector(0))", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "CLICKS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nus_redirect_click_thru or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CLICK THRU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      { "expr": "nus_redirect_click_thru", "legendFormat": "{{id}}" },
      { "expr": "sum(nus_redirect_click_thru)", "legendFormat": "Total" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nus_action{job=\"shortnr\"}",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nus_logs{job=\"shortnr\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MONGODB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"mgob\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "SUCCESSFUL BACKUPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mgob_scheduler_backup_total{status=\"200\", plan=~\"tacobot|shortnr\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED BACKUPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mgob_scheduler_backup_total{status!=\"200\", plan=~\"tacobot|shortnr\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A + $B + $C", "type": "math" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 3, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_user_join_leave{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tacobot_system_actions{action=\"NEW_ACCOUNT_KICK\"}",
       "legendFormat": "NEW ACCOUNT KICK"
      }
     ]
    },
    {
     "title": "Stream Team Requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_team_requests{instance=\"$collector\"} ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_live_now{guild_id=~\"$guild_id\"}",
       "legendFormat": "🔴 LIVE NOW"
      }
     ]
    },
    {
     "title": "Gone Live 🔴",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_live_platform {guild_id=~\"$guild_id\", platform!=\"GRAND THEFT AUTO VI\"}",
       "legendFormat": "{{platform}}"
      }
     ]
    },
    {
     "title": "Invited Users",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tacobot_invites {guild_id=~\"$guild_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Twitch Linked Accounts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tacobot_twitch_linked_accounts", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Giveaway Games Available",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_game_keys_available{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Giveaway Games Redeemed",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_game_keys_redeemed{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FREE GAMES",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tacobot_free_game_keys", "legendFormat": "{{state}}" }
     ]
    },
    {
     "title": "Twitch Bot Joined Channels",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_twitch_channels{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Minecraft Whitelisted",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_minecraft_whitelist{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SHiFT CODES",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tacobot_shift_codes", "legendFormat": "{{state}}" }
     ]
    },
    {
     "title": "SHiFT CODES TRACKED",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_shift_codes_tracked{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_birthdays{guild_id=~\"$guild_id\"}",
       "legendFormat": "BIRTHDAYS"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_logs{guild_id=~\"$guild_id\", level=~\"WARNING|ERROR|FATAL\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Twitch Tacos🌮",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_twitch_tacos {guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Tacos Earned",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_tacos {guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tacos Gifted",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_taco_gifts {guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🌮 Reactions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_taco_reactions {guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_user_status{guild_id=~\"$guild_id\", status!=\"UNKNOWN\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "User Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "tacobot_user_status{guild_id=~\"$guild_id\", status!=\"UNKNOWN\"}",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "TQOTD Questions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_tqotd {guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mental Mondays Topics",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_mentalmondays{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Taco Tuesday",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_tacotuesday {guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WDYCTW Questions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_wdyctw_questions{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tech Thursdays Topics",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_techthurs{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "First Messages Today",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tacobot_first_messages_today{guild_id=~\"$guild_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Known Users",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tacobot_known_users{guild_id=~\"$guild_id\"}) by (type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TQOTD Answers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_tqotd_answers{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mental Mondays Interactions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_mentalmondays_answers{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Taco Tuesday Interactions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_tacotuesday_answers{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WDYCTW Answers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_wdyctw_answers{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tech Thursdays Replies",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_techthurs_answers{guild_id=~\"$guild_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages Tracked Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tacobot_messages{guild_id=~\"$guild_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Introduction Posts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tacobot_introductions{guild_id=~\"$guild_id\"}) by (approved)",
       "legendFormat": "{{approved}}"
      }
     ]
    },
    {
     "title": "Photo Posts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 164 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tacobot_photo_posts{guild_id=~\"$guild_id\"}) by (channel)",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Suggestions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 170 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tacobot_suggestions{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Photo Post Rate By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "round(delta(tacobot_photo_posts{guild_id=~\"$guild_id\"}[1d]))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Photo Post By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "sum(tacobot_photo_posts{guild_id=~\"$guild_id\"}) by (username)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Photo Post Rate By Channel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "sum(round(delta(tacobot_photo_posts{guild_id=~\"$guild_id\"}[1d]))) by (channel) ",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Photo Post By Channel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "targets": [
      {
       "expr": "sum(tacobot_photo_posts{guild_id=~\"$guild_id\"}) by (channel)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Rate By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "targets": [
      {
       "expr": "round(delta(tacobot_messages{guild_id=~\"$guild_id\"}[30m]))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Messages By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
     "targets": [
      {
       "expr": "tacobot_messages{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Interaction Topics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 177 },
     "targets": [
      {
       "expr": "round(delta(tacobot_mentalmondays{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Mental Monday"
      },
      {
       "expr": "round(delta(tacobot_tacotuesday{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Taco Tuesday"
      },
      {
       "expr": "round(delta(tacobot_wdyctw_questions{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "WDYCTW"
      },
      {
       "expr": "round(delta(tacobot_techthurs{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Tech Thursday"
      },
      {
       "expr": "round(delta(tacobot_tqotd{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "TQOTD"
      }
     ]
    },
    {
     "title": "Interactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 177 },
     "targets": [
      {
       "expr": "round(delta(tacobot_tqotd_answers{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "TQOTD"
      },
      {
       "expr": "round(delta(tacobot_mentalmondays_answers{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Mental Monday"
      },
      {
       "expr": "round(delta(tacobot_tacotuesday_answers{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Taco Tuesday"
      },
      {
       "expr": "round(delta(tacobot_wdyctw_answers{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "WDYCTW"
      },
      {
       "expr": "round(delta(tacobot_techthurs_answers{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Tech Thursday"
      }
     ]
    },
    {
     "title": "Message Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 177 },
     "targets": [
      {
       "expr": "sum(round(delta(tacobot_messages{guild_id=~\"$guild_id\"}[30m])))",
       "legendFormat": "Messages"
      },
      {
       "expr": "round(delta(tacobot_first_messages_today{guild_id=~\"$guild_id\"}[60m]))",
       "legendFormat": "First Message"
      }
     ]
    },
    {
     "title": "Trivia Starter and Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "targets": [
      {
       "expr": "sum(tacobot_trivia_questions{guild_id=~\"$guild_id\"}) by (starter_name)",
       "legendFormat": "{{starter_name}}"
      },
      {
       "expr": "sum(tacobot_trivia_questions{guild_id=~\"$guild_id\"}) by (difficulty)",
       "legendFormat": "{{difficulty}}"
      }
     ]
    },
    {
     "title": "Trivia By Category",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "targets": [
      {
       "expr": "sum(tacobot_trivia_questions{guild_id=~\"$guild_id\"}) by (category)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Visuals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Games Redeemed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "tacobot_user_game_keys_redeemed{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "User Games Submitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "tacobot_user_game_keys_submitted{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Stream Avatar Wins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "tacobot_twitch_stream_avatar_duel_winners{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Tacos By Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "tacobot_taco_logs{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Tacos Rate By Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "delta(tacobot_taco_logs{guild_id=~\"$guild_id\"}[60m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Reacts By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "tacobot_reactors {guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "React Rate By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 111 },
     "targets": [
      {
       "expr": "round(delta(tacobot_reactors {guild_id=~\"$guild_id\"}[30m]))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Gift Rate By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "round(delta(tacobot_gifters{guild_id=~\"$guild_id\"}[30m]))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Gift By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "tacobot_gifters{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Total Tacos By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "tacobot_top_tacos{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Tacos Rate By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 119 },
     "targets": [
      {
       "expr": "round(delta(tacobot_top_tacos{guild_id=~\"$guild_id\"}[30m]))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "User Invites",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tacobot_invites{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "TACOs 🌮",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 127 },
     "targets": [
      {
       "expr": "tacobot_taco_gifts {guild_id=~\"$guild_id\"}",
       "legendFormat": "Gifts"
      },
      {
       "expr": "tacobot_taco_reactions {guild_id=~\"$guild_id\"}",
       "legendFormat": "Reactions"
      },
      {
       "expr": "tacobot_twitch_tacos {guild_id=~\"$guild_id\"}",
       "legendFormat": "Twitch"
      }
     ]
    },
    {
     "title": "Tacos 🌮 Earned",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 127 },
     "targets": [
      {
       "expr": "tacobot_tacos{guild_id=~\"$guild_id\"}",
       "legendFormat": "TACOS 🌮"
      }
     ]
    },
    {
     "title": "Taco Receive Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "round(delta(tacobot_tacos{guild_id=~\"$guild_id\"}[30m]))",
       "legendFormat": "Earned"
      },
      {
       "expr": "round(delta(tacobot_taco_gifts{guild_id=~\"$guild_id\"}[60m]))",
       "legendFormat": "Gift"
      },
      {
       "expr": "round(delta(tacobot_taco_reactions{guild_id=~\"$guild_id\"}[60m]))",
       "legendFormat": "Reactions"
      },
      {
       "expr": "round(delta(tacobot_twitch_tacos{guild_id=~\"$guild_id\"}[60m]))",
       "legendFormat": "Twitch"
      }
     ]
    },
    {
     "title": "Exporter Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "targets": [
      { "expr": "tacobot_exporter_errors", "legendFormat": "{{source}}" }
     ]
    },
    {
     "title": "Logs Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 143 },
     "targets": [
      {
       "expr": "round(delta(tacobot_logs{guild_id=~\"$guild_id\"}[60m]))\r\n",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 143 },
     "targets": [
      {
       "expr": "tacobot_logs{guild_id=~\"$guild_id\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔴LIVE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "🔴 Live By User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "tacobot_live_activity {guild_id=~\"$guild_id\", platform!=\"\"}",
       "legendFormat": "{{username}} ({{platform}})"
      }
     ]
    },
    {
     "title": "🔴 LIVE NOW",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "targets": [
      {
       "expr": "tacobot_live_now{guild_id=~\"$guild_id\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "sum(avg_over_time(tacobot_live_now{guild_id=~\"$guild_id\"}[24h]))",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  }
 ]
}