---
##########################
##########################
## OpenAPI Linter rules ##
##########################
##########################

extends: spectral:oas

rules:
  no-$ref-siblings: off
  no-ref-siblings: off
