---
# python scripts/swagger_sync.py --check --markdown-summary=openapi_summary.md --models-root=bot/lib/models --handlers-root=bot/lib/http/handlers/ --swagger-file=.swagger.v1.yaml --output-directory=./reports/openapi/ --coverage-report=openapi_coverage.json --show-missing-blocks --coverage-format=json --verbose-coverage --show-orphans --strict
swagger-file: .swagger.v1.yaml
models-root: bot/lib/models
handlers-root: bot/lib/http/handlers
output-directory: ./reports/openapi/
markdown-summary: openapi_summary.md
coverage-report: openapi_coverage.json
strict: true
show-orphans: false
show-ignored: false
show-missing-blocks: true
coverage-format: json
verbose-coverage: true
check: true
fix: false
