# OpenAPI/Swagger Synchronization Configuration
# yaml-language-server: $schema=../../scripts/swagger_sync/config_schema.json
#
# This file configures the swagger_sync.py script for this project.
# All paths are relative to the directory containing this file.
#
# Usage:
#   python scripts/swagger_sync.py --check
#   python scripts/swagger_sync.py --check --env=ci
#   python scripts/swagger_sync.py --fix
#

version: '1.0'
swagger_file: .swagger.v1.yaml
handlers_root: bot/lib/http/handlers/
models_root: bot/lib/models/
output:
  directory: ./reports/openapi/
  coverage_report: openapi-coverage.json
  coverage_format: json  # Options: json, text, cobertura (or 'xml' as alias for cobertura)
  badge: ./docs/badges/openapi-coverage.svg
mode: check
options:
  strict: false
  show_orphans: true
  show_missing_blocks: true
  verbose_coverage: true
  color: auto
markers:
  start: '>>>openapi'
  end: <<<openapi
ignore:
  files:
  - '**/test_*.py'
  - '**/__pycache__/**'
  handlers:
  - internal_health_check
  - debug_endpoint
environments:
  ci:
    mode: check
    options:
      color: never
      strict: true
      show_orphans: true
      show_missing_blocks: true
      verbose_coverage: true
    output:
      markdown_summary: openapi-summary.md
      coverage_report: openapi-coverage.xml
      coverage_format: xml  # XML/cobertura format for CI/CD systems

  local:
    mode: check
    output:
      markdown_summary: openapi-summary.md
      coverage_report: openapi-coverage.xml
      coverage_format: xml  # XML/cobertura format for local testing
    options:
      strict: true
      show_orphans: true
      show_missing_blocks: true
      verbose_coverage: true
  quiet:
    mode: check
    output: null
    options:
      show_orphans: false
      show_missing_blocks: false
      verbose_coverage: false
      strict: false
