---
disable-telemetry: true
exit-code: 1
exit-on-eol: 2
scan:
  skip-dirs:
    - .devcontainer/
    - __pycache__/
    - .vscode/
    - .github/
    - tests/
  scanners:
    - vuln
    - misconfig
    - secret
