---
name: Swagger Sync Check
on:
  pull_request:
    paths:
      - 'bot/**'
      - '.swagger.v1.yaml'
      - 'scripts/swagger_sync.py'
  push:
    branches:
      - develop
      - beta*
permissions: {}
jobs:
  swagger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Swagger sync check
        run: |
          python scripts/swagger_sync.py \
            --check \
            --handlers-root bot/lib/http/handlers/ \
            --swagger-file .swagger.v1.yaml \
            --output-directory reports \
            --markdown-summary openapi_summary.md \
            --coverage-report openapi_coverage.json \
            --show-missing-blocks \
            --coverage-format json \
            --verbose-coverage \
            --show-orphans

      - name: Upload OpenAPI reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openapi-reports
          path: reports/
          if-no-files-found: warn
